version: "3.7"
services:
  database:
    container_name: database-localdev
    image: mariadb:latest
    expose:
      - 3306
    ports:
      - "3307:3306"
    volumes:
      - ./db/data:/var/lib/mysql:rw
      - ./db/init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_USER: user
      MARIADB_PASSWORD: pass
    networks:
      - backend-dev
    restart: always

  api:
    container_name: api-localdev
    build:
      context: ./../../backend/devenv-backend
    expose:
      - 80
    ports:
      - "5000:80"
    networks:
      - backend-dev
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DevenvConnectionString: "Server=database-localdev;Port=3306;Uid=root;Pwd=secret;Database=userdb;sslmode=none;"


  api-mock:
    image: mockoon/cli:latest
    container_name: mockapi-localdev
    command: -d https://raw.githubusercontent.com/HansenBerlin/devenv-api-mock/main/doc/data.json -p 3000
    ports:
      - "3001:3000"
    networks:
      - backend-dev

networks:
  backend-dev:
    name: devenv-local-backend-network  
    driver: bridge

         