version: "3.7"
services:
  database:
    container_name: devenv-db
    image: mariadb:latest
    expose:
      - 3306
    ports:
      - "3307:3306"
    volumes:
      - ./../../db/data:/var/lib/mysql:rw
      - ./../../db/init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_USER: user
      MARIADB_PASSWORD: pass
    networks:
      - backend
    restart: always

  api:
    container_name: devenv-minimalapi
    image: devenv-api
    expose:
      - 80
    ports:
      - "5000:80"
    networks:
      - backend
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  api-mock:
    image: mockoon/cli:latest
    container_name: devenv-mockapi
    command: -d https://raw.githubusercontent.com/HansenBerlin/devenv-api-mock/main/doc/data.json -p 3000
    ports:
      - "3000:3000"
    volumes:
      - ./../../devenv-api-mock/doc:/usr/share/nginx/html/doc
    networks:
      - backend
    environment:
      API_URL: doc/swagger.yaml

networks:
  backend:
    name: devenv-local-backend-network  
    driver: bridge

         