version: "3.7"
services:
  nginx_local_dev_proxy:
    container_name: devenv-rp-staging
    image: 139.162.185.180:5000/devenv-nginx
    ports:
      - "1443:443"      
    volumes:
      - "./nginx/conf/:/etc/nginx/conf.d/:rw"
    networks:
      - frontend-production
    depends_on:
      - api
      - frontend
    restart: always
    command: [nginx-debug, '-g', 'daemon off;']

  database:
    container_name: database
    image: mariadb:latest
    expose:
      - 3306
    volumes:
      - ./db/data:/var/lib/mysql:rw
      - ./db/init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_USER: user
      MARIADB_PASSWORD: pass
    networks:
      - backend-production
    restart: always

  api:
    container_name: api
    image: 139.162.185.180:5000/devenv-api:latest
    expose:
      - 80
    networks:
      - backend-production
    environment:
      DevenvConnectionString: "Server=database;Port=3306;Uid=root;Pwd=secret;Database=userdb;sslmode=none;"
    restart: always

  frontend:
    container_name: frontend
    image: 139.162.185.180:5000/devenv-frontend:latest
    networks:
      - backend-production
      - frontend-production
    expose:
      - 80
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      UsersEndpoint: "http://api/users"

networks:
  backend-production:
    name: backend-nw-production
    driver: bridge
  frontend-production:
    name: frontend-nw-production
    driver: bridge

         