version: "3.7"
services:
  database:
    container_name: devenv-db-e2e
    image: mariadb:latest
    expose:
      - 3306
    volumes:
      - ./db/data:/var/lib/mysql:rw
      - ./db/init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_USER: user
      MARIADB_PASSWORD: pass
    networks:
      - backend-e2e
    restart: always

  api:
    container_name: devenv-minimalapi-e2e
    image: devenv-api
    expose:
      - 80
    networks:
      - backend-e2e
    restart: always

  frontend:
    container_name: devenv-fe-e2e
    image: devenv-frontend
    networks:
      - backend-e2e
      - frontend-e2e
    expose:
      - 80
    restart: always
    environment:
      UsersEndpoint: "http://devenv-minimalapi-e2e/users"

networks:
  backend-e2e:
    name: devenv-backend-network-e2e
    driver: bridge
  frontend-e2e:
    name: devenv-frontend-network-e2e
    driver: bridge

         