version: "3.7"
services:
  frontend:
    container_name: devenv-fe-integration-testing
    image: devenv-frontend
    networks:
      - integration-testing
    expose:
      - 80
    ports:
      - "5003:80"
    restart: always
    environment:
      UsersEndpoint: "http://devenv-mockapi-integration-testing:3001/users"
  
  api-mock:
    image: mockoon/cli:latest
    container_name: devenv-mockapi-integration-testing
    command: -d https://raw.githubusercontent.com/HansenBerlin/devenv-api-mock/main/doc/data.json -p 3001
    ports:
      - "3001:3001"
    networks:
      - integration-testing

networks:
  integration-testing:
    name: devenv-integration-testing-nw
    driver: bridge

         